language: python
python:
    - "2.7"
install:
    - sudo apt-get --reinstall install -qq language-pack-en language-pack-fr
    - "pip install -r requirements.txt"
script: nosetests cmakesnippets tests